import { LanguageDictionary } from "../utils/TranslationUtils";
export const en: LanguageDictionary = {
  // ... (existing translations)
    coolOffers: {
    vipPackage: {
      title: "VIP Package",
      subtitle: "High-Level Telegram App with Smart Access, Custom User Progression & AI Guidance",
      description: "Get the ultimate Telegram app, loaded with smart access controls, progressive unlocking, and an AI-powered tab to help users build out new features as they go.",
      feature1: "Full Custom Interface & UX",
      feature2: "Supabase with Full RLS & Custom Role Setup",
      feature3: "AI-Powered Dev Tab for Content Creation",
      feature4: "Step-by-Step User Learning & Engagement",
      feature5: "Multi-Stage Role Access"
    },
    aiAutomation: {
      title: "AI Automation Pipeline Setup",
      description: "Set up an AI-driven automation pipeline tailored to your needs. Perfect for agencies, product sites, or any project that requires a scalable, high-efficiency web automation setup.",
      feature1: "Custom AI automation pipeline configuration",
      feature2: "Component integration & automated deployment",
      feature3: "Advanced control panel for managing updates",
      feature4: "Instructions and ongoing support"
    },
    standardPackage: {
      title: "Standard Package",
      subtitle: "Advanced Telegram App with Stepwise Access & Learning System",
      description: "Get an advanced Telegram mini app with custom role access, data security, and phased feature unlocking.",
      feature1: "Advanced Interface",
      feature2: "Enhanced User Data Security with Row Level Security",
      feature3: "Custom Role & Access Setup",
      feature4: "Stepwise Feature Unlocking"
    },
    aiComponents: {
      title: "AI-Powered Web Components",
      description: "Get custom AI-powered web components tailored to your project's needs, ensuring a seamless user experience and compatibility across devices.",
      feature1: "Custom AI-driven component development",
      feature2: "Responsive design and cross-platform functionality",
      feature3: "Full testing and integration support",
      feature4: "Post-deployment support"
    },
    basicPackage: {
      title: "Basic Package",
      subtitle: "Essential Telegram Mini App with User Data & Role Access",
      description: "Get a basic Telegram mini app that handles user data, simple role-based access, and a clean, straightforward interface.",
      feature1: "Basic Interface",
      feature2: "Simple User Data Setup",
      feature3: "Role-Based Access Control",
      feature4: "Core Tabs Only"
    },
    aiWebsite: {
      title: "AI-Powered Website Creation",
      description: "Get a professional, responsive website built using advanced AI tools, ensuring it's visually striking and optimized for conversions.",
      feature1: "AI-based custom design",
      feature2: "Responsive layouts for mobile and desktop",
      feature3: "Basic SEO optimization",
      feature4: "100% stress-free process"
    }
    },
 "before:": "Before:",
  "after:": "After:",
  "onboarding": {
    "welcome": "Welcome to Hack the System 🔧",
    "description": "Break the rules. Rewire reality. Redefine control. 🧠💥",
    "intro": "In Hack the System, you're about to enter a world where power isn't given, it's taken. Guided by Xuinity, your AI mentor, you'll learn to exploit the cracks in the system, hack the boundaries of control, and unlock hidden potential that most can’t even see.",
    "keyFeatures": "Key Features 😏:",
    "features": {
      "deceptiveSimplicityTitle": "Deceptive Simplicity",
      "deceptiveSimplicityDesc": "Start with seemingly basic games that hide a deeper reality. 🎮",
      "crashTitle": "The Crash",
      "crashDesc": "Discover the hidden 'Hack the System' button and witness a simulated system crash that reveals the true nature of the game. 💻",
      "visualProgrammingTitle": "Visual Programming",
      "visualProgrammingDesc": "Learn coding concepts through an intuitive, visual interface. 🤖",
      "bitMatrixTitle": "The Bit Matrix",
      "bitMatrixDesc": "Manipulate the very fabric of the game world, and by extension, reality itself. 💡",
      "ethicalDilemmasTitle": "Ethical Dilemmas",
      "ethicalDilemmasDesc": "Face moral choices that impact the game world and challenge your perception of right and wrong. ⚖️",
      "blurredRealityTitle": "Blurred Reality",
      "blurredRealityDesc": "Experience a game that constantly questions the boundaries between the virtual and the real. 🌐"
    },
    "conclusion": "This isn't just a game. It's a rebellion against limitations, a journey into the heart of technology's potential, and a stark warning about the power we wield in the digital age. Ready to hack the system, or will the system hack you? 😈",
    "enterButton": "Enter the System 🚀"
  },
  "steps": {
    "collect": "Collect",
    "generate": "Generate",
    "enhance": "Enhance",
    "review": "Review",
    "push": "Push"
  },
  bottomShelf: {
      paymentNotification: "Payment",
      dynamicItemForm: "Items",
      qrCodeForm: "QR Code",
      cryptoPayment: "Crypto",
      home: "Home",
      rent: "Rent",
      referral: "Refer",
      profile: "Profile",
      quests: "Quests",
      bets: "Bets",
      quiz: "Quiz",
      createEvent: "Event",
      conflictAwareness: "Conflict",
      admin: "Admin",
      dev: "Dev",
      versimcel: "VersimCel",
    customComponent1: "Custom 1",
      customComponent2: "Custom 2",
      customComponent3: "Custom 3",
      questsForCoins: "Quests",
    },
"chooseUnlock": "Choose a Component to Unlock",
    "betsComponent": "Bets Component",
    "betsDescription": "Unlock the Bets component to start placing wagers and increasing your odds.",
    "unlockBets": "Unlock Bets",
    "rentsComponent": "Rents Component",
    "rentsDescription": "Unlock the Rents component to manage and invest in properties.",
    "unlockRents": "Unlock Rents",
  visitV0: "Visit v0.dev",
  viewGitHubRepo: "View GitHub Repo",
  checkVercelDeployments: "Check Vercel Deployments",
    contact: {
     
    "heading": "Get in Touch",

      title: "Get Started Today!",
      description: "Experience the future of web development with v0. Let our AI bring your vision to life effortlessly.",
      playGameButton: "Play Game",
      contactUs: "Contact us on Telegram",
    },
    "gigs": {
    "title": "Our Services on Contra",
    "service1Title": "Move existing web site to v0",
    "service1Description": "Let us seamlessly transition your existing website to the v0 platform.",
    "service1Price": "$69.13",
    "service1LinkText": "Hire on Contra",
    "service2Title": "Create custom v0 projects",
    "service2Description": "Custom website creation tailored to your specific needs using v0's AI capabilities.",
    "service2Price": "$69.13",
    "service2LinkText": "Hire on Contra",
    service1Link:"https://contra.com/s/lXMUXEXe-move-existing-web-site-to-framer",
    service2Link:"https://contra.com/s/RggeLso3-create-landing-paywall-membership-e-market-sites-and-more",
  },
  "benefits": {
    "title": "Why Choose v0?",
    "benefit1Title": "Global Accessibility",
    "benefit1Description": "Create websites that are accessible and performant worldwide.",
    "benefit2Title": "Security First",
    "benefit2Description": "Built-in security features to keep your website and data safe.",
    "benefit3Title": "Collaborative Tools",
    "benefit3Description": "Seamlessly work with your team on web projects."
  },
  "footer": {
    "socialTitle": "Connect With Us",
    "aboutTitle": "About v0",
    "aboutDescription": "Empowering developers and businesses with AI-enhanced tools for effortless web creation.",
    "quickLinksTitle": "Quick Links",
    "quickLink1": "Home",
    "quickLink2": "Features",
    "quickLink3": "Pricing",
    "quickLink4": "Templates",
    "quickLink5": "Instructions",
    "quickLink6": "Automation",
    "quickLink7": "Mobile Shop",
    "quickLink8": "FAQ",
    "quickLink9": "Contact",
    "copyright": "© 2024 v0 AI Dev."
  },

  


      pricing: {
        title: "Pricing Title",
        options: "Pricing Options",
        heading: "Pricing Plans",
        basic: "BASIC",
        pro: "PRO",
        enterprise: "ENTERPRISE",
        feature1: "AI-powered design",
        feature2: "Responsive layout",
        feature3: "Basic SEO optimization",
        proFeature1: "All BASIC features",
        proFeature2: "Advanced customization",
        proFeature3: "Priority support",
        proFeature4: "Performance analytics",
        enterpriseFeature1: "All PRO features",
        enterpriseFeature2: "Unlimited pages",
        enterpriseFeature3: "Custom integrations",
        enterpriseFeature4: "Dedicated account manager",
        choosePlan: "Choose Plan",
      },
      templates: {
        heading: "Explore v0 Templates",
        description:
          "Unleash your creativity with our extensive collection of AI-generated templates, meticulously crafted to cater to diverse tastes and requirements.",
        unhuilome: "UnHuilome",
        unhuilomeDesc: "Versatile template for various projects",
        ezShop: "EZ Shop",
        ezShopDesc: "Quick and easy e-commerce solution",
        promo: "Promo",
        promoDesc: "Promotional landing page template",
        domiki: "Domiki",
        domikiDesc: "Real estate and property showcase",
        viewTemplate: "View Template",
      },
      instructions: {
        heading: "How to Use v0 Templates",
        description:
          "Check out our simple guide on how to maximize the potential of your AI-powered website templates.",
        viewInstructions: "View Instructions",
      },
      "mobileShop": {
  "description": "Explore Mobile Shop: Unleash your creativity with our extensive collection of Mobile Shop templates, meticulously curated to cater to diverse tastes and requirements. And the best part? We handle everything for you! From crafting the perfect logo and palette to optimizing SEO-rich content for every section of your website, even handling payments seamlessly. Simply sit back, relax, and watch your dream website come to life.",
        heading: "Mobile Shop",
        title: "Mobile Shop Interface",
      },
      faq: {
    "question1": "What are the stages of the AutomationPipeline?",
    "answer1": "The AutomationPipeline consists of five main stages: 1) Collect - gathering necessary data, 2) Generate - creating initial code, 3) Enhance - improving and optimizing the code, 4) Review - checking for quality and consistency, and 5) Push - integrating the component into the project repository.",
    "question2": "How does the game progression work?",
    "answer2": "The game progression is divided into stages. Players start at stage 0 and advance by completing tasks, unlocking new features, and making choices. Each stage introduces new components and challenges, allowing players to build and expand their virtual business.",
    "question3": "What happens when I unlock a new component?",
    "answer3": "When you unlock a new component, the AutomationPipeline simulates its creation and integration into your project. You'll see the process unfold in real-time, from data collection to code generation and final deployment. This new component will then become available for use in your game.",
    "question4": "Can I influence the direction of my game progression?",
    "answer4": "Yes! At certain stages, you'll be presented with choices that affect your game's direction. These could be selecting different types of businesses to pursue, choosing between various upgrades, or deciding on different strategies. Your choices will shape your unique game experience.",
    "question5": "How do side hustles work in the game?",
    "answer5": "Side hustles are additional activities or mini-games that you can engage in alongside your main business. They offer opportunities to earn extra in-game currency, unlock special achievements, or gain advantages in your primary business. You'll encounter options for side hustles as you progress through the game stages.",
        heading: "Frequently Asked Questions",
        whatIsV0: "What is v0?",
        whatIsV0Answer:
          "v0 is our groundbreaking AI-driven web development platform that enables users to create stunning websites with minimal effort.",
        howDoesAIWork: "How does AI work in v0?",
        howDoesAIWorkAnswer:
          "Our AI algorithms analyze user inputs to generate customized website designs and functionalities tailored to their needs.",
        customDomain: "Can I use a custom domain?",
        customDomainAnswer:
          "Yes, all of our plans include support for custom domains.",
        freeTrial: "Is there a free trial?",
        freeTrialAnswer:
          "Yes, we offer a free 7-day trial for all new users to explore our platform.",
        isProgrammingObsolete: "Does v0 make programming obsolete?",
        isProgrammingObsoleteAnswer:
          "No, while v0 automates many tasks, programming skills are still essential for more advanced customizations.",
        programmingTeachesThinking: "Why is programming still important?",
        programmingTeachesThinkingAnswer:
          "Programming teaches problem-solving and logical thinking, skills that remain valuable even with AI-driven tools like v0.",
        programmingWithNewTools: "Can I combine programming with v0?",
        programmingWithNewToolsAnswer:
          "Absolutely! You can integrate your own code to enhance your v0-powered website with additional custom features.",
      },

    




  "header": {
    "title": "v0 AI Dev"
  },
  "nav": {
    "home": "Home",
    "features": "Features",
    "pricing": "Pricing",
    "templates": "Templates",
    "instructions": "Instructions",
    "mobile-shop": "Mobile Shop",
    "faq": "FAQ",
    "contact": "Contact",
    "automation": "Automation"
  },
  "home": {
    "heading": "Unlock Success with v0 AI",
    "description": "Embark on a transformative web development journey with v0, your ultimate AI-powered solution for creating stunning websites effortlessly.",
    "imageAlt": "AI-powered web development",
    "watchVideos": "Watch Our Videos"
  },
  "features": {
    "heading": "Key Features",
    "aiPowered": "AI-Powered Magic",
    "aiPoweredDesc": "Let our cutting-edge AI take the lead in crafting mesmerizing websites.",
    "effortlessCreation": "Effortless Creation",
    "effortlessCreationDesc": "Watch your dream website materialize in just days, stress-free.",
    "customizableTemplates": "Customizable Templates",
    "customizableTemplatesDesc": "Kickstart your project with our handcrafted, customizable templates."
  },
  
  "storyEditor": "Story Editor",
  "editStage": "Edit Stage",
  "addNewStage": "Add New Stage",
  
'Learn More on NotebookLM': "Learn More about LATOKEN on NotebookLM",
  xuinitySays: "XUINITY Says",
  cardImgUrl: "Card sprite URL",
  shirtImgUrl: "Shirt image URL",
  yeetCoefficient: "Yeet Coefficient",
  yeetVelocityThreshold: "Velocity Threshold",
  tooHigh: "too High",
  tooLow: "too Low",
  incorrectGuess: "Incorrect Guess",
  outOfAttempts: "Out Of Attempts",
  hackingFailed: "Hacking Failed",
  guessedNumber: "You guessed number in {{attempts}} attempts",
  hackingSuccessful: "Hacking Successful",
  failedToProgress: "Failed To Progress",
  sideHustleUnlocked: "Side Hustle Unlocked",
  achievementUnlocked: "Achievement Unlocked",
  "activateHackButton": "Activate Hack Button",
  "guessTheNumber": "Guess the Number",
  "guessInstructions": "Guess a number between 1 and 13",
  "enterGuess": "Enter your guess",
  "submitGuess": "Submit Guess",
  "correctGuess": "Correct! You guessed the number!",
  "guessTooLow": "Too low. Try again!",
  "guessTooHigh": "Too high. Try again!",
  "attempts": "Attempts: {{count}}",
  "unlockedVoiceActivation": "You've unlocked voice activation!",
  "skinCustomization": "Skin Customization",
  "stageProgression": "Stage Progression",
  "unlockedHackButton": "You've unlocked the Hack Button!",
  "unlockedSkinCustomization": "You've unlocked skin customization!",
  "unlockedCryptoPrices": "You've unlocked crypto prices in the Skin Shop!",
  "notEnoughCoins": "Not enough coins to purchase this skin",
  "skinPurchased": "Skin purchased successfully",
  "skinShop": "Skin Shop",
  "loadingSkins": "Loading skins...",
  "featuredSkins": "Featured Skins",
  "yourSkins": "Your Skins",
  "keepPlayingToUnlock": "Keep playing to unlock more features!",
  "buySkin": "Buy Skin",
  mileage: "Mileage",
  pay: "Pay",
  backToCreators:"Back to Creators",
  pleaseGrantAccess: "Please grant access to your camera and microphone to play the game.",
  checkPermissions: "Check Permissions",
  "tension": "Tension",
  setDefault: "Set Default",
  "rotationDistance": "Rotation Distance",
  "friction": "Friction",
  "minMovementThreshold": "Min Movement Threshold",
    saveAndContinueInTelegram: "Save And Continue In Telegram",
    copy: "Copy Request to Clipboard",
    saveRefCode: "Save",
    name: "English",
    welcome: "Welcome",
    task: "Task",
    description: "Description",
    addTask: "Add Task",
    complete: "Complete",
    delete: "Delete",
    // UI
    referrals: "Referrals",
    top13: "Leaderboard",
    menu: "Menu",
    startGame: "Start Game",
    endGame: "End Game",
    yourScore: "Your Score",
    topScores: "Top Scores",
    about: {
      info: 'Info',
      title: 'About the App',
      motto: 'The app is designed to create web3 environments freely, and commercial use is supported out of the box by crypto.',
      github: 'View on GitHub',
      version: 'App v. 0.13',
    },
    quests: "Quests",
    open: "Open",
    create: "Create a game",
    inviteText: "Join our app:",
    invitePlayButton: "Play Fool",
    invitePlayLable: "Get invite",
    gameLobby: "Game Lobby",
    gameID: "Game ID:",
    readyPlayers: "Ready Players:",
    gameBoard: "Game Board",
    trumpSuit: "Trump Suit:",
    playersHands: "Players' Hands",
    joinGame: "Join Game",
    player: "Player: ",
    lang: "Language",
    questStart: "Start",
    questClaim: "Claim",
    // Game Titles and General
    game_title: "Fool Game",
    loading_game_state: "Loading game state...",
    welcome_message: "Welcome to Fool Game!",
    waiting_for_players: "Waiting for players to join...",
    game_over: "Game Over",
    you_won: "You Won!",
    you_lost: "You Lost!",
    draw: "It's a Draw!",
    // Gameplay
    current_turn: "Current Turn",
    your_turn: "Your Turn",
    opponent_turn: "Opponent's Turn",
    select_card: "Select a Card",
    place_card: "Place the Card",
    invalid_move: "Invalid Move!",
    move_successful: "Move Successful!",
    round_start: "Round Start",
    round_end: "Round End",
    next_round: "Next Round",
    // Player Actions
    draw_card: "Draw a Card",
    pass: "Pass",
    attack: "Attack",
    defend: "Defend",
    end_turn: "End Turn",
    quit_game: "Quit Game",
    // Notifications and Messages
    message: "Message",
    new_message: "New Message",
    player_joined: "Player Joined",
    player_left: "Player Left",
    waiting_for_opponent: "Waiting for opponent...",
    opponent_disconnected: "Opponent Disconnected",
    connection_lost: "Connection Lost. Reconnecting...",
    // Game Stats and Info
    player_stats: "Player Stats",
    player_name: "Player Name",
    player_score: "Player Score",
    player_level: "Player Level",
    player_coins: "Player Coins",
    player_xp: "Player XP",
    leaderboard: "Leaderboard",
    top_players: "Top Players",
    // Game Settings
    change_language: "Change Language",
    music: "Music",
    sound_effects: "Sound Effects",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    // Quests and Rewards
    daily_quests: "Daily Quests",
    weekly_quests: "Weekly Quests",
    completed_quests: "Completed Quests",
    claim_reward: "Claim Reward",
    reward_claimed: "Reward Claimed!",
    new_quest: "New Quest Available",
    // Errors and Warnings
    error_occurred: "An Error Occurred",
    try_again: "Please Try Again",
    game_not_found: "Game Not Found",
    action_not_allowed: "Action Not Allowed",
    invalid_action: "Invalid Action",
    // Miscellaneous
    yes: "Yes",
    no: "No",
    ok: "OK",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    skip: "Skip",
    continue: "Continue",
    exit: "Exit",
    calcTitle: "IQ/social indicators calculator",
    active: "Active",
    activeBets: "Active Bets and Events",
    amount: "Amount",
    outcome: "Outcome",
    status: "Status",
    upcomingEvents: "Upcoming Events",
    title: "Title",
    actions: "Actions",
    expired: "Expired",
    bet: "Bet",
    placeBet: "Place Bet",
    enterBetAmount: "Enter Bet Amount",
    referFriend: "Refer a Friend",
    friendNamePlaceholder: "Friend's Name",
    inviteFriendButton: "Invite Friend",
    inviteMessage: "Hey {name}, join me on this amazing platform! Click the link below to get started:",
    referAFriend: "Refer a Friend",
    inviteFriend: "Invite a Friend via Telegram",
    friendName: "Friend's Name",
    sendInvite: "Send Invite",
    inviteSent: "Invite Sent Successfully!",
    alreadyReferred: "This user has already been referred.",
    error: "An error occurred. Please try again.",
    profile: "Profile",
    createEvent: "Create Event",
    eventTitle: "Event Title",
    eventDescription: "Event Description",
    eventTitleRu: "Event Title In Russian",
    eventDescriptionRu: "Event Description In Russian",
    educationalVideoUrl: "Educational Video URL",
    expirationDate: "Expiration Date",
    eventCreated: "Event Created",
    eventCreationSuccessMessage: "The event has been successfully created",
    close: "Close",
    homeShelf: "Home",
    admin: "Admin",
    referral: "Referral",
    referralName: "Priglos Name",
    adminDashboard: "Admin Dashboard",
    totalReferrals: "Total Referrals",
    referralsLastMonth: "Referrals Last Month",
    referralsLastYear: "Referrals Last Year",
    referrer: "Referrer",
    referee: "Referee",
    refCode: "Referral Code",
    date: "Date",
    referralsByCode: "Referrals by Code",
    successfulInvites: "Successful Invites",
    rank: "Lvl",
    username: "Nickname",
    level: "Level",
    notifications: "Notifications",
    nonewnotifications: "You have no new notifications.",
    play: "Play",
    playWithUs: "Play with",
    startPlaying: "Start Playing",
    visitSite: "Visit Our Site",
    joinCommunity: "Join Our Community",
    youtubeChannel: "Subscribe to Our YouTube",
    profilePicture: "Profile Picture",
    userId: "ID",
    coins: "Coins",
    rp: "Reputation Points",
    X: "X Points",
    cheers_count: "Cheers Count",
    social_credit: "Social Credit",
    ref_code: "Referral Code",
    currentGameId: "Current Game ID",
    none: "None",
    pending: "Pending",
    in_progress: "In Progress",
    completed: "Completed",
    failed: "Failed",
    cancelled: "Cancelled",
    not_started: "Not Started",
    referral_sent: "Referral Sent",
    referral_accepted: "Referral Accepted",
    quest_started: "Quest Started",
    quest_completed: "Quest Completed",
    subtitle: {
      githubManager: "GitHub Manager",
    },
    button: {
      createBranch: "Create Branch",
      pushFiles: "Push Files to Branch",
      mergeBranch: "Merge Branch to Main",
    },
    log: {
      filePushed: "File {fileName} pushed to branch {branchName} with commit SHA {newCommitSha}.",
      branchMerged: "Branch {branchName} merged into main.",
      rollback: "Branch {branchName} rolled back to commit SHA {sha}.",
    },
    suberror: {
      createBranch: "Failed to create branch",
      pushFiles: "Failed to push files to branch",
      mergeBranch: "Failed to merge branch into main",
      rollback: "Failed to rollback to commit",
      branchRequired: "Branch name is required",
      translationFieldsRequired: "Please specify a language and provide translations.",
      updateTranslations: "Failed to update translations",
    },
    success: {
      translationsUpdated: "Translations updated successfully.",
    },
    hackButton: "Hack the System",
    congratulationsMessage: "You hacked the system!",

    questsTitle: "Quests to Earn Coins",
    inviteFriends: "Invite Friends",
    inviteFriendsDescription: "Invite 3 friends through referrals to earn coins.",
    inviteFriendsAction: "Invite Now",
    createFeature: "Create Your First Feature",
    createFeatureDescription: "Create your first feature in dev mode to earn coins.",
    createFeatureAction: "Create Feature",
    claimReward: "Claim Reward",
    developerToolTitle: "Developer Tool",
  currentIdeasTitle: "Current Ideas",
  enterYourIdeaTitle: "Enter Your Idea",
  describeYourIdeaPlaceholder: "Describe your idea...",
  generateRequestButton: "Generate Request",
   generateRequestButton4type: "Generate Request for New Type", 
  zeroStageRequestTitle: "Zero Stage Request",
  getResponseButton: "Get Response from Clipboard",
  parsedResponseDataTitle: "Parsed Response Data",
  branchNameTitle: "Branch Name",
  componentImplementationsTitle: "Component Implementations",
  translationKeysTitle: "Translation Keys",
  supabaseTablesTitle: "Supabase Tables",
  readmeUpdateTitle: "README.md Update",
  tryItButton: "Try It",
  deployButton: "Deploy",
  contributorsLabel: "Contributors",
  emotionMirror: "Emotion Mirror",
  typeMessage: "Type your message here...",
  clear: "Clear",
  conflictAwarenessTitle: "Conflict Awareness and Humanitarian Support",
  realTimeUpdates: "Real-Time Updates",
  educationalResources: "Educational Resources",
  interactiveMaps: "Interactive Maps",
  humanitarianAid: "Humanitarian Aid and Donations",
  discussionForums: "Discussion Forums",
  impactAnalytics: "Impact Analytics",
  donateNow: "Donate Now",
  postComment: "Post a Comment",
  premiumLandingPages: "Premium Custom Landing Pages",
    requestLandingPage: "Request New Landing Page",
    landingPageName: "Landing Page Name",
    view: "View",
    noLandingPages: "You have no custom landing pages yet.",
    cryptoPayment: "Crypto Payment",
    generatePaymentLink: "Generate Payment Link",
    paymentLinkGenerated: "Payment link has been generated:",
    invalidAmount: "Invalid amount.",
    errorGeneratingLink: "Error generating payment link.",
    qrCodeTitle: "Continue on Another Device",
    qrCodeDescription: "Scan this QR code with your mobile device to continue filling out the form.",
    generateQrCode: "Generate QR Code",
    dynamicForm: "Dynamic Form",
    submit: "Submit",
    itemAddedSuccessfully: "Item added successfully, please refresh the page",
    paymentSuccessMessage: "Hello, {username}! Your payment was successful. Your premium access will be activated by {activationDate}.",
    notificationSent: "Notification sent successfully!",
    resendNotification: "Resend Notification",
    defaultLabel: "TBD",
    disableOptionLabel: "Service not provided",
    
    formTypes: {
      evo: "Tow Truck",
      car: "Car",
      motorbike: "Motorbike",
      bicycle: "Bicycle",
      dota2: "Dota 2",
      promtgramming: "Promtgramming",
      AI: "AI",
    },
  
    // Form Labels
    selectCity: "Select City",
    enterYourName: "Enter your name",
    mobileNumber: "Mobile Number",
    landlineNumber: "Landline Number",
    email: "Your email",
    parkingAddress: "Tow Truck Parking Address",
    adTitle: "Ad Title",
    adDescription: "Ad Description",
    cars: "Cars",
    motorcycles: "Motorcycles",
    suvs: "SUVs",
    minibus: "Minibus",
    suburbanTariff: "Suburban Tariff",
    attachPhoto: "Attach Photo",
    agreeToTerms: "I agree to the terms of service and the processing of my data.",
    
    // Buttons
    upload: "Upload",
    rent: "Rent",
    rentsTitle: "My Rentals",
    addNewItem: "Add New Item",
    activeRentals: "Active Rentals",
    itemTitle: "Item Title",
    rentStart: "Rent Start",
    rentEnd: "Rent End",
    newItems: "New Items",
    creatorShop: "Creator's Shop",
    addNewItemTitle: "Add a New Item",
    addNewItemDescription: "Fill in the details for the new item",
    errorProcessingWithdrawal: "Error processing withdrawal",
    cryptoWithdrawal: "Crypto Withdrawal",
    processWithdrawal: "Process Withdrawal",
    withdrawalProcessed: "Withdrawal processed successfully",
    cryptoManagement: "Crypto Management",
    site: "Site",
    telegramUsername: "Telegram Username",
    walletAddress: "Wallet Address",
    payment: {
        title: "Payment",
        description: "Description of the payment process"
      },
      adInfo: {
        titleLabel: "Title",
        descriptionLabel: "Description",
        title: "Ad information",
        fields: {
          title: "Ad title",
          description: "Ad description",
        },
      },
      agreement: {
        title: "Consent",
        fields: {
    consent: "I agree with the terms of use of the service...",
        },
      },
      generalOnfo: {
        makeLabel: "Make",
        yearLabel: "Year",
        colorLabel: "Color",
        modelLabel: "Model",
        priceLabel: "Price",
        title: "General information",
        fields: {
          make: "Brand",
          model: "Model",
          year: "Year of issue",
          color: "Color",
          price: "Price",
          mileage: "Mileage",
        },
      },
      photoUpload: {
        photoLabel: "Photo",
        photoAlt: "Item Photo",
        title: "Photo",
        fields: {
            photo: "Photography",
        },
      },
      rentStartDate: "Rent Start Date",
      rentEndDate: "Rent End Date",
      calculatePrice: "Calculate Price",
      totalPrice: "Total Price",
      proceedToPayment: "Proceed to Payment",
      itemDetailsTitle: "Item Details",
      itemDetailsDescription: "Description",
      newRentNotification: "Someone attempted to rent your item",
      viewItem: "View Item",
    common: {
      n_a: "N/A"
    },
    newItemTypeNameRequest: "Enter a name for the new item type:",
    save: "Save New Item Type",
    gpt: "Oops! Failed to make sense of that JSON. Need some help? Check out the Dev page!",
    gptTypeName: "Whoa! That name's already taken. Try something unique.",
    emptyTypeName: "Oops! You forgot to give it a name. Can't save without one!",
    enterTitleKey: "Enter a cool title for your new item type",
    enterJsonData: "Paste your JSON magic here",
    errorInsert: "Yikes! Something went wrong while saving. Please try again.",
    noData: "No Data",
    generalInfo: "General Information",
    city: "City",
    russian: "Russian",
    yourEmail: "Your Email",
  "settings": {
    title: "Settings",
    restoreDefaults: "Restore Defaults",
    mass: "Mass",
    tension: "Tension",
    friction: "Friction",
    rotationDistance: "Rotation Distance",
    minMovementThreshold: "Min Movement Threshold",
    github: "View on GitHub",
    version: "Version 0.13"
  },
  "physicsSettings": "Settings",
  applySettings: "Apply",
    photos: "Photos",
    rentalStartDate: "Rental Start Date",
    rentalEndDate: "Rental End Date",
    carsCount: "Cars: 13",
    suvsCount: "SUVs: 56",
    minibusCount: "Minibus: 23",
    motorcyclesCount: "Motorcycles: 26",
    suburbanTariffCount: "Suburban Tariff: 56",
    dota2: "Dota 2",
ff: "FF",
nickname: "Nickname",
dcfc: "DCFC",
tiltLevel: "Tilt Level",
noTilt: "Not Tilting",
discordTag: "Discord Tag",
memeBuilds: "Meme Builds",
soloLesson: "Solo Lesson",
partyLesson: "Party Lesson",
favoriteHero: "Favorite Hero",
preferredRole: "Preferred Role",
support: "Support",
replayAnalysis: "Replay Analysis",
inGameCoaching: "In-Game Coaching",
make: "Make",
year: "Year",
color: "Color",
model: "Model",
price: "Price",
agreementSectionTitle: "Consent",
car: "Car",
motorbike: "Motorbike",
bicycle: "Bicycle",
evo: "Evacuator",
ai: "AI",
groupLesson: "Group Nerd Herd",
promptReview: "Prompt Roast",
projectAssistance: "Project S.O.S.",
promtgramming: "Code Whispering",
darkTheme: "Dark Theme",
shuffle: "ShufFle Cards",
shuffling: "Shuffling..",
gravity: "Gravity",
airFriction: "Air Friction",
surfaceFriction: "Surface Friction",
mass: "Mass",
liftCoefficient: "Lift Coefficient",
minRotationSpeedForLift: "Min Rotation Speed for Lift",
presets: "Presets",
selectPreset: "Select a preset",
"Lunar Gravity": "Lunar Gravity",
"Earth Gravity": "Earth Gravity",
"No Air Friction": "No Air Friction",
"Jupiter Gravity": "Jupiter Gravity",
createTask: "Create Task",
  serverName: "Server Name",
  inviteLink: "Invite Link",
  membersNeeded: "Members Needed",
  activeTasks: "Active Tasks",
  deleteTask: "Delete Task",
  userPoints: "User Points",
  serverId: "Server ID",
  points: "Points",
  tasks: "Tasks",
  users: "Users",
  promoteToAdmin: "Promote to Admin",
  role: "Role",
  socialCredit: "Social Credit",
  adminData: "Admin Data",
  subscriptions: "Subscriptions",
  botMessages: "Bot Messages",
  rewardPoint: "Reward Point",
  checkSubscription: "Check Subscription",
  taskId: "Task ID",
  createQuest: "Create Quest",
  questTitle: "Quest Title",
  questDescription: "Quest Description",
  questType: "Quest Type",
  questReward: "Quest Reward",
  questCategory: "Quest Category",
  questImageUrl: "Quest Image URL",
  questTarget: "Quest Target",
  questSocialLink: "Quest Social Link",
  tracking: "Tracking",
  social: "Social",
  questStates: "Quest States",
  activeQuests: "Active Quests",
  deleteQuest: "Delete Quest",
  questId: "Quest ID",
  state: "State",
  progress: "Progress",
  streak: "Streak",
  checkReferrals: "Check Referrals",
  referredUserId: "Referred User ID",
  search: "Search",
  totalUsers: "Total Users",
  cryptopayment: "₿",
  avatarUrl: "Avatar Pic Link",
  playCards: "Play Card Game",
  playDice: "Play Dice Game",
  backToMenu: "Back to Menu",
  userNotFound: "User not found",
  updateCoinsError: "Error updating coins",
  generalError: "An error occurred. Please try again.",
  diceGame: "Dice Game",
  score: "Score",
  player1: "Player 1",
  player2: "Player 2",
  rollDice: "Roll Dice",
  newGame: "New Game",
  twoPlayerMode: "Two Player Mode",
  aiMode: "AI Mode",
  randomOpponentMode: "Random Opponent",
  backToSinglePlayer: "Back to Single Player",
  rules: "Rules",
  rulesText: "Roll the dice and try to get the highest score. In two-player mode, take turns rolling. The player with the highest score wins!",
  rolling: "Rolling...",
  singlePlayer: "Single Player",
  twoPlayer: "Two Players",
  playWithAI: "Play with AI",
  randomOpponent: "Random Opponent",
  winner: "Winner",
  noActiveGame: "No active game found",
  updateError: "Update Error",
  updateErrorDescription: "Failed to update game state. Please try again.",
  hackSuccess: "Hack Successful",
  newGameAdded: "New game added to the list",
  hackError: "Hack Error",
  tryAgainLater: "Please try again later",
  hacking: "Hacking...",
  hack: "Hack",
  currentTurn: "Current Turn",
  turn: "turn",
  rentNow: "Rent Now",
  
  developerDashboard: "Developer Dashboard",
  welcomeToDevTab: "Welcome to the Dev Tab",
  devTabInstructions: "Follow these steps to contribute to the project:",
  step1Description: "Generate an AI request for your idea",
  step2Description: "Copy the generated request and paste it into v0.dev",
  step3Description: "Review the generated code and make any necessary adjustments",
  step4Description: "Submit your changes through GitHub and deploy with Vercel",
  openV0Dev: "Open v0.dev",
  requestGeneratedSuccess: "Request generated successfully! Click 'Copy to Clipboard' to use it.",
  githubProjectIntegration: "GitHub Project Integration",
  githubProjectDescription: "View and manage tasks in the GitHub project board:",
  openGitHubProject: "Open GitHub Project",
  viewProjectComponents: "View Project Components",
  vercelDeployment: "Vercel Deployment",
  vercelDeploymentDescription: "Monitor and manage deployments on Vercel:",
  openVercelDashboard: "Open Vercel Dashboard",
  achievements: "Achievements",
  requestGenerationAchievement: "Request Generator",
  requestGenerationDescription: "Generate AI requests to improve the platform",
  getStartedWithGitHub: "Get Started with GitHub",
  githubAccountInstructions: "To contribute, you'll need a GitHub account. Create one now:",
  createGitHubAccount: "Create GitHub Account",
  notifySalavey13: "Notify Salavey13",
  v0DevLinkPlaceholder: "Paste v0.dev shared chat link here",
  githubTaskLinkPlaceholder: "Paste GitHub task link here",
  sendNotification: "Send Notification",
  vpnAccess: "VPN Access",
  pleaseProvideLinks: "Please provide both v0.dev and GitHub task links.",
  notificationFailed: "Failed to send notification. Please try again.",
  achievement_request_generation_title: "Request Generator",
  achievement_request_generation_description: "Generate AI requests to improve the platform",
  achievement_bug_fixes_title: "Bug Squasher",
  achievement_bug_fixes_description: "Fix bugs and improve the platform",
  achievement_feature_implemented_title: "Feature Maestro",
  achievement_feature_implemented_description: "Implement new features for the platform",
  achievement_successful_deployment_title: "Deployment Dynamo",
  achievement_successful_deployment_description: "Successfully deploy new features",
  welcomeSection: "Dev's Launchpad 🚀",
  ideaSection: "Idea Incubator 💡",
  projectSection: "Project Mission Control 🎛️",
  achievementsSection: "Trophy Cabinet 🏆",
  notifySection: "Bat-Signal for Salavey13 🦇",
  SubmitAnswer: "Submit Answer",
  unlock: "Unlock",
  "devKit": {
    "stageNumber": "Stage Number",
"notSet": "Not Set",
noParentStage: "No Parent Stage",
storyContent: "Content",
xuinityDialog: "Dialog",

trigger: "Trigger",

activeComponent: "Active Component",

minigame: "Minigame",

achievement: "Achievement",


bottomShelfBitmask: "Bottom Shelf Bitmask",

parentStage: "Parent Stage",

editStage: "Edit Stage",
addNewStage: "Add New Stage",

xuinitySays: "XUINITY Says",
    showUnlockChoice: "Show Unlock Choice",
    failedToFetchStoryStages: "Failed to Fetch Story Stages",
    crashSimulated: "Oops! It Crashed!",
    simulateCrash: "Crash it",
    title: 'Dev Kit',
    gameState: 'Game State',
    storyEdit: 'Story Edit',
    stats: 'Stats',
    selectStage: 'Select Stage',
    coins: 'Coins',
    crypto: 'Crypto',
    applyChanges: 'Apply Changes',
    playersPerStage: 'Players per Stage',
    stage: 'Stage',
    players: 'players',
    success: 'Success',
    error: 'Error',
    gameStateUpdated: 'Game state updated successfully',
    failedToUpdateGameState: 'Failed to update game state',
    hideDevKit: "- DevKit -",
    showDevKit: "DevKit",
    addComponent: "Add Component",
      newComponentName: "New Component Name",
      newComponentIcon: "New Component Icon",
      newComponentStageMask: "New Component Stage Mask",
      addNewComponent: "Add New Component",
      newComponentFieldsRequired: "Component name and icon are required",
      newComponentAdded: "New component added successfully",
    bottomShelfComponents: "Bit Matrix",
  },
  stats: "Stats",
  wallet: "Wallet",
  "automation": {
    "heading": "Automation Pipeline",
    "description": "Watch our AI-powered automation pipeline in action as it creates and integrates new components.",
    "watch": "Watch the magic happen",
    "startingCreation": "Starting creation of component {componentName}...",
    "dataCollected": "Data collected for component {componentName}",
    "codeGenerated": "Code generated for {componentName}.tsx",
    "codeEnhanced": "Enhanced code for component {componentName}",
    "componentReviewed": "Reviewed and approved component {componentName}",
    "componentPushed": "Component {componentName} successfully added to the repository",
    "creationSuccess": "Component {componentName} successfully created and integrated",
    "creationError": "Error creating component {componentName}: {errorMessage}",
    "automationInProgress": "Automation in progress",
    "automationComplete": "Automation complete",
    "visitV0": "Visit v0.dev",
    "viewGitHubRepo": "View GitHub Repo",
    "checkVercelDeployments": "Check Vercel Deployments"
  }
}
