import { LanguageDictionary } from "../utils/TranslationUtils";
export const en: LanguageDictionary = {
  "yeetCoefficient": "Yeet Coefficient",
  "tension": "Tension",
  "rotationDistance": "Rotation Distance",
  "friction": "Friction",
  "yeetVelocityThreshold": "Yeet Velocity Threshold",
  "minMovementThreshold": "Min Movement Threshold",
    saveAndContinueInTelegram: "Save And Continue In Telegram",
    copy: "Copy Request to Clipboard",
    saveRefCode: "Save",
    name: "English",
    welcome: "Welcome",
    task: "Task",
    description: "Description",
    addTask: "Add Task",
    complete: "Complete",
    delete: "Delete",
    // UI
    settings: "Settings",
    referrals: "Referrals",
    top13: "Leaderboard",
    menu: "Menu",
    startGame: "Start Game",
    endGame: "End Game",
    yourScore: "Your Score",
    topScores: "Top Scores",
    about: {
      info: 'Info',
      title: 'About the App',
      motto: 'The app is designed to create web3 environments freely, and commercial use is supported out of the box by crypto.',
      github: 'View on GitHub',
      version: 'App v. 0.13',
    },
    quests: "Quests",
    open: "Open",
    create: "Create a game",
    inviteText: "Join our app:",
    invitePlayButton: "Play Fool",
    invitePlayLable: "Get invite",
    gameLobby: "Game Lobby",
    gameID: "Game ID:",
    readyPlayers: "Ready Players:",
    gameBoard: "Game Board",
    trumpSuit: "Trump Suit:",
    playersHands: "Players' Hands",
    joinGame: "Join Game",
    player: "Player: ",
    lang: "Language",
    questStart: "Start",
    questClaim: "Claim",
    // Game Titles and General
    game_title: "Fool Game",
    loading_game_state: "Loading game state...",
    welcome_message: "Welcome to Fool Game!",
    waiting_for_players: "Waiting for players to join...",
    game_over: "Game Over",
    you_won: "You Won!",
    you_lost: "You Lost!",
    draw: "It's a Draw!",
    // Gameplay
    current_turn: "Current Turn",
    your_turn: "Your Turn",
    opponent_turn: "Opponent's Turn",
    select_card: "Select a Card",
    place_card: "Place the Card",
    invalid_move: "Invalid Move!",
    move_successful: "Move Successful!",
    round_start: "Round Start",
    round_end: "Round End",
    next_round: "Next Round",
    // Player Actions
    draw_card: "Draw a Card",
    pass: "Pass",
    attack: "Attack",
    defend: "Defend",
    end_turn: "End Turn",
    quit_game: "Quit Game",
    // Notifications and Messages
    message: "Message",
    new_message: "New Message",
    player_joined: "Player Joined",
    player_left: "Player Left",
    waiting_for_opponent: "Waiting for opponent...",
    opponent_disconnected: "Opponent Disconnected",
    connection_lost: "Connection Lost. Reconnecting...",
    // Game Stats and Info
    player_stats: "Player Stats",
    player_name: "Player Name",
    player_score: "Player Score",
    player_level: "Player Level",
    player_coins: "Player Coins",
    player_xp: "Player XP",
    leaderboard: "Leaderboard",
    top_players: "Top Players",
    // Game Settings
    change_language: "Change Language",
    music: "Music",
    sound_effects: "Sound Effects",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    // Quests and Rewards
    daily_quests: "Daily Quests",
    weekly_quests: "Weekly Quests",
    completed_quests: "Completed Quests",
    claim_reward: "Claim Reward",
    reward_claimed: "Reward Claimed!",
    new_quest: "New Quest Available",
    // Errors and Warnings
    error_occurred: "An Error Occurred",
    try_again: "Please Try Again",
    game_not_found: "Game Not Found",
    action_not_allowed: "Action Not Allowed",
    invalid_action: "Invalid Action",
    // Miscellaneous
    yes: "Yes",
    no: "No",
    ok: "OK",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    skip: "Skip",
    continue: "Continue",
    exit: "Exit",
    calcTitle: "IQ/social indicators calculator",
    active: "Active",
    activeBets: "Active Bets and Events",
    amount: "Amount",
    outcome: "Outcome",
    status: "Status",
    upcomingEvents: "Upcoming Events",
    title: "Title",
    actions: "Actions",
    expired: "Expired",
    bet: "Bet",
    placeBet: "Place Bet",
    enterBetAmount: "Enter Bet Amount",
    referFriend: "Refer a Friend",
    friendNamePlaceholder: "Friend's Name",
    inviteFriendButton: "Invite Friend",
    inviteMessage: "Hey {name}, join me on this amazing platform! Click the link below to get started:",
    referAFriend: "Refer a Friend",
    inviteFriend: "Invite a Friend via Telegram",
    friendName: "Friend's Name",
    sendInvite: "Send Invite",
    inviteSent: "Invite Sent Successfully!",
    alreadyReferred: "This user has already been referred.",
    error: "An error occurred. Please try again.",
    profile: "Profile",
    createEvent: "Create Event",
    eventTitle: "Event Title",
    eventDescription: "Event Description",
    eventTitleRu: "Event Title In Russian",
    eventDescriptionRu: "Event Description In Russian",
    educationalVideoUrl: "Educational Video URL",
    expirationDate: "Expiration Date",
    eventCreated: "Event Created",
    eventCreationSuccessMessage: "The event has been successfully created",
    close: "Close",
    home: "Home",
    admin: "Admin",
    referral: "Referral",
    referralName: "Priglos Name",
    adminDashboard: "Admin Dashboard",
    totalReferrals: "Total Referrals",
    referralsLastMonth: "Referrals Last Month",
    referralsLastYear: "Referrals Last Year",
    referrer: "Referrer",
    referee: "Referee",
    refCode: "Referral Code",
    date: "Date",
    referralsByCode: "Referrals by Code",
    successfulInvites: "Successful Invites",
    rank: "Lvl",
    username: "Nickname",
    level: "Level",
    notifications: "Notifications",
    nonewnotifications: "You have no new notifications.",
    play: "Play",
    playWithUs: "Play with",
    startPlaying: "Start Playing",
    visitSite: "Visit Our Site",
    joinCommunity: "Join Our Community",
    youtubeChannel: "Subscribe to Our YouTube",
    profilePicture: "Profile Picture",
    userId: "ID",
    coins: "Coins",
    rp: "Reputation Points",
    X: "X Points",
    cheers_count: "Cheers Count",
    social_credit: "Social Credit",
    ref_code: "Referral Code",
    currentGameId: "Current Game ID",
    none: "None",
    pending: "Pending",
    in_progress: "In Progress",
    completed: "Completed",
    failed: "Failed",
    cancelled: "Cancelled",
    not_started: "Not Started",
    referral_sent: "Referral Sent",
    referral_accepted: "Referral Accepted",
    quest_started: "Quest Started",
    quest_completed: "Quest Completed",
    subtitle: {
      githubManager: "GitHub Manager",
    },
    button: {
      createBranch: "Create Branch",
      pushFiles: "Push Files to Branch",
      mergeBranch: "Merge Branch to Main",
    },
    log: {
      filePushed: "File {fileName} pushed to branch {branchName} with commit SHA {newCommitSha}.",
      branchMerged: "Branch {branchName} merged into main.",
      rollback: "Branch {branchName} rolled back to commit SHA {sha}.",
    },
    suberror: {
      createBranch: "Failed to create branch",
      pushFiles: "Failed to push files to branch",
      mergeBranch: "Failed to merge branch into main",
      rollback: "Failed to rollback to commit",
      branchRequired: "Branch name is required",
      translationFieldsRequired: "Please specify a language and provide translations.",
      updateTranslations: "Failed to update translations",
    },
    success: {
      translationsUpdated: "Translations updated successfully.",
    },
    hackButton: "Hack the System",
    congratulationsMessage: "You hacked the system!",

    questsTitle: "Quests to Earn Coins",
    inviteFriends: "Invite Friends",
    inviteFriendsDescription: "Invite 3 friends through referrals to earn coins.",
    inviteFriendsAction: "Invite Now",
    createFeature: "Create Your First Feature",
    createFeatureDescription: "Create your first feature in dev mode to earn coins.",
    createFeatureAction: "Create Feature",
    claimReward: "Claim Reward",
    developerToolTitle: "Developer Tool",
  currentIdeasTitle: "Current Ideas",
  enterYourIdeaTitle: "Enter Your Idea",
  describeYourIdeaPlaceholder: "Describe your idea...",
  generateRequestButton: "Generate Request",
   generateRequestButton4type: "Generate Request for New Type", 
  zeroStageRequestTitle: "Zero Stage Request",
  getResponseButton: "Get Response from Clipboard",
  parsedResponseDataTitle: "Parsed Response Data",
  branchNameTitle: "Branch Name",
  componentImplementationsTitle: "Component Implementations",
  translationKeysTitle: "Translation Keys",
  supabaseTablesTitle: "Supabase Tables",
  readmeUpdateTitle: "README.md Update",
  tryItButton: "Try It",
  deployButton: "Deploy",
  contributorsLabel: "Contributors",
  emotionMirror: "Emotion Mirror",
  typeMessage: "Type your message here...",
  clear: "Clear",
  conflictAwarenessTitle: "Conflict Awareness and Humanitarian Support",
  realTimeUpdates: "Real-Time Updates",
  educationalResources: "Educational Resources",
  interactiveMaps: "Interactive Maps",
  humanitarianAid: "Humanitarian Aid and Donations",
  discussionForums: "Discussion Forums",
  impactAnalytics: "Impact Analytics",
  donateNow: "Donate Now",
  postComment: "Post a Comment",
  premiumLandingPages: "Premium Custom Landing Pages",
    requestLandingPage: "Request New Landing Page",
    landingPageName: "Landing Page Name",
    view: "View",
    noLandingPages: "You have no custom landing pages yet.",
    cryptoPayment: "Crypto Payment",
    generatePaymentLink: "Generate Payment Link",
    paymentLinkGenerated: "Payment link has been generated:",
    invalidAmount: "Invalid amount.",
    errorGeneratingLink: "Error generating payment link.",
    qrCodeTitle: "Continue on Another Device",
    qrCodeDescription: "Scan this QR code with your mobile device to continue filling out the form.",
    generateQrCode: "Generate QR Code",
    dynamicForm: "Dynamic Form",
    submit: "Submit",
    itemAddedSuccessfully: "Item added successfully, please refresh the page",
    paymentSuccessMessage: "Hello, {username}! Your payment was successful. Your premium access will be activated by {activationDate}.",
    notificationSent: "Notification sent successfully!",
    resendNotification: "Resend Notification",
    defaultLabel: "TBD",
    disableOptionLabel: "Service not provided",
    
    formTypes: {
      evo: "Tow Truck",
      car: "Car",
      motorbike: "Motorbike",
      bicycle: "Bicycle",
      dota2: "Dota 2",
      promtgramming: "Promtgramming",
      AI: "AI",
    },
  
    // Form Labels
    selectCity: "Select City",
    enterYourName: "Enter your name",
    mobileNumber: "Mobile Number",
    landlineNumber: "Landline Number",
    email: "Your email",
    parkingAddress: "Tow Truck Parking Address",
    adTitle: "Ad Title",
    adDescription: "Ad Description",
    cars: "Cars",
    motorcycles: "Motorcycles",
    suvs: "SUVs",
    minibus: "Minibus",
    suburbanTariff: "Suburban Tariff",
    attachPhoto: "Attach Photo",
    agreeToTerms: "I agree to the terms of service and the processing of my data.",
    
    // Buttons
    upload: "Upload",
    rent: "Rent",
    rentsTitle: "My Rentals",
    addNewItem: "Add New Item",
    activeRentals: "Active Rentals",
    itemTitle: "Item Title",
    rentStart: "Rent Start",
    rentEnd: "Rent End",
    newItems: "New Items",
    creatorShop: "Creator's Shop",
    addNewItemTitle: "Add a New Item",
    addNewItemDescription: "Fill in the details for the new item",
    errorProcessingWithdrawal: "Error processing withdrawal",
    cryptoWithdrawal: "Crypto Withdrawal",
    processWithdrawal: "Process Withdrawal",
    withdrawalProcessed: "Withdrawal processed successfully",
    cryptoManagement: "Crypto Management",
    site: "Site",
    telegramUsername: "Telegram Username",
    walletAddress: "Wallet Address",
    payment: {
        title: "Payment",
        description: "Description of the payment process"
      },
      adInfo: {
        titleLabel: "Title",
        descriptionLabel: "Description",
        title: "Ad information",
        fields: {
          title: "Ad title",
          description: "Ad description",
        },
      },
      agreement: {
        title: "Consent",
        fields: {
    consent: "I agree with the terms of use of the service...",
        },
      },
      generalOnfo: {
        makeLabel: "Make",
        yearLabel: "Year",
        colorLabel: "Color",
        modelLabel: "Model",
        priceLabel: "Price",
        title: "General information",
        fields: {
          make: "Brand",
          model: "Model",
          year: "Year of issue",
          color: "Color",
          price: "Price",
          mileage: "Mileage",
        },
      },
      photoUpload: {
        photoLabel: "Photo",
        photoAlt: "Item Photo",
        title: "Photo",
        fields: {
            photo: "Photography",
        },
      },
      rentStartDate: "Rent Start Date",
      rentEndDate: "Rent End Date",
      calculatePrice: "Calculate Price",
      totalPrice: "Total Price",
      proceedToPayment: "Proceed to Payment",
      itemDetailsTitle: "Item Details",
      itemDetailsDescription: "Description",
      newRentNotification: "Someone attempted to rent your item",
      viewItem: "View Item",
    common: {
      n_a: "N/A"
    },
    newItemTypeNameRequest: "Enter a name for the new item type:",
    save: "Save New Item Type",
    gpt: "Oops! Failed to make sense of that JSON. Need some help? Check out the Dev page!",
    gptTypeName: "Whoa! That name's already taken. Try something unique.",
    emptyTypeName: "Oops! You forgot to give it a name. Can't save without one!",
    enterTitleKey: "Enter a cool title for your new item type",
    enterJsonData: "Paste your JSON magic here",
    errorInsert: "Yikes! Something went wrong while saving. Please try again.",
    noData: "No Data",
    generalInfo: "General Information",
    city: "City",
    russian: "Russian",
    yourEmail: "Your Email",
    pricing:{
        title: "Pricing Title",
        options: "Pricing Options",
    },
  "settings": {
    "title": "Settings",
    "restoreDefaults": "Restore Defaults",
    "yeetCoefficient": "Yeet Coefficient",
    "mass": "Mass",
    "tension": "Tension",
    "friction": "Friction",
    "rotationDistance": "Rotation Distance",
    "yeetVelocityThreshold": "Yeet Velocity Threshold",
    "minMovementThreshold": "Min Movement Threshold",
    "github": "View on GitHub",
    "version": "Version 0.13"
  },
    photos: "Photos",
    rentalStartDate: "Rental Start Date",
    rentalEndDate: "Rental End Date",
    carsCount: "Cars: 13",
    suvsCount: "SUVs: 56",
    minibusCount: "Minibus: 23",
    motorcyclesCount: "Motorcycles: 26",
    suburbanTariffCount: "Suburban Tariff: 56",
    dota2: "Dota 2",
ff: "FF",
nickname: "Nickname",
dcfc: "DCFC",
tiltLevel: "Tilt Level",
noTilt: "Not Tilting",
discordTag: "Discord Tag",
memeBuilds: "Meme Builds",
soloLesson: "Solo Lesson",
partyLesson: "Party Lesson",
favoriteHero: "Favorite Hero",
preferredRole: "Preferred Role",
support: "Support",
replayAnalysis: "Replay Analysis",
inGameCoaching: "In-Game Coaching",
make: "Make",
year: "Year",
color: "Color",
model: "Model",
price: "Price",
agreementSectionTitle: "Consent",
car: "Car",
motorbike: "Motorbike",
bicycle: "Bicycle",
evo: "Evacuator",
ai: "AI",
groupLesson: "Group Nerd Herd",
promptReview: "Prompt Roast",
projectAssistance: "Project S.O.S.",
promtgramming: "Code Whispering",
darkTheme: "Dark Theme",
shufle: "shufle Cards",
gravity: "Gravity",
airFriction: "Air Friction",
surfaceFriction: "Surface Friction",
mass: "Mass",
liftCoefficient: "Lift Coefficient",
minRotationSpeedForLift: "Min Rotation Speed for Lift",
presets: "Presets",
selectPreset: "Select a preset",
"Lunar Gravity": "Lunar Gravity",
"Earth Gravity": "Earth Gravity",
"No Air Friction": "No Air Friction",
"Jupiter Gravity": "Jupiter Gravity",
}
