import { LanguageDictionary } from "../utils/TranslationUtils";
export const ru: LanguageDictionary = {
    newItemTypeNameRequest: "Введите имя для нового типа элемента:",
    saveRefCode: "Сохранить",
    newRentNotification: "Кто-то пытался арендовать ваш предмет",
    viewItem: "Просмотреть элемент",
    rent: "Аренда",
    saveAndContinueInTelegram: "Сохранить и продолжить в Telegram",
    paymentSuccessMessage: "Привет, {username}! Ваш платеж был успешным. Премиум доступ будет активирован к {activationDate}.",
    notificationSent: "Уведомление успешно отправлено!",
    resendNotification: "Отправить уведомление снова",
    dynamicForm: "Динамическая форма",
    submit: "Отправить",
    itemAddedSuccessfully: "Элемент успешно добавлен, зарефреште страницу",
    qrCodeTitle: "Продолжить на другом устройстве",
    qrCodeDescription: "Сканируйте этот QR-код на мобильном устройстве, чтобы продолжить заполнение формы.",
    generateQrCode: "Создать QR-код",
    emotionMirror: "Зеркало эмоций",
    typeMessage: "Введите ваше сообщение...",
    clear: "Очистить",
    developerToolTitle: "Инструмент разработчика",
  currentIdeasTitle: "Текущие идеи",
  enterYourIdeaTitle: "Введите свою идею",
  describeYourIdeaPlaceholder: "Опишите свою идею...",
  generateRequestButton: "Сгенерировать запрос",
  generateRequestButton4type: "Сгенерировать тип обьявы",
  zeroStageRequestTitle: "Запрос боту",
  getResponseButton: "Получить ответ из буфера обмена",
  parsedResponseDataTitle: "Проанализированные данные ответа",
  branchNameTitle: "Название ветки",
  componentImplementationsTitle: "Реализации компонентов",
  translationKeysTitle: "Ключи перевода",
  supabaseTablesTitle: "Таблицы супабазы",
  readmeUpdateTitle: "Обновление README.md",
  tryItButton: "Попробуй",
  deployButton: "Развернуть",
contributorsLabel: "Соавторы",
    questsTitle: "Задания для заработка монет",
    inviteFriends: "Пригласите друзей",
    inviteFriendsDescription: "Пригласите 3 друзей по реферальной ссылке, чтобы заработать монеты.",
    inviteFriendsAction: "Пригласить сейчас",
    createFeature: "Создайте свою первую функцию",
    createFeatureDescription: "Создайте свою первую функцию в режиме разработки, чтобы заработать монеты.",
    createFeatureAction: "Создать функцию",
    claimReward: "Получить награду",
    copy: "Скопировать в буфер",
    adminDashboard: "Панель администратора",
    totalReferrals: "Всего рефералов",
    referralsLastMonth: "Рефералы за последний месяц",
    referralsLastYear: "Рефералы за последний год",
    referrer: "Реферер",
    referee: "Реферал",
    refCode: "Код реферала",
    date: "Дата",
    referralsByCode: "Рефералы по коду",
    referrals: "Рефералы",
    name: "Русский",
    profile: "Профиль",
    profilePicture: "Фото профиля",
    userId: "ID",
    coins: "Монеты",
    rp: "Очки репутации",
    X: "X Очки",
    cheers_count: "Количество одобрений",
    social_credit: "Социальный рейтинг",
    ref_code: "Реферальный код",
    currentGameId: "ID текущей игры",
    none: "Нет",
    welcome: "Добро пожаловать",
    task: "Задача",
    description: "Описание",
    addTask: "Добавить задачу",
    complete: "Завершить",
    delete: "Удалить",
    active: "Активный",
    activeBets: "Активные ставки и события",
    amount: "Сумма",
    outcome: "Результат",
    status: "Статус",
    upcomingEvents: "Предстоящие События",
    title: "Название",
    actions: "Действия",
    expired: "Истек",
    bet: "Наспор",
    placeBet: "Сделать Ставку",
    enterBetAmount: "Введите Сумму Ставки",
    confirm: "Подтвердить",
    calcTitle: "Калькулятор IQ/социальных показателей",
    friendNamePlaceholder: "Friend's Name",
    inviteFriendButton: "Invite Friend",
    inviteMessage: "Hey {name}, join me on this amazing platform! Click the link below to get started:",
    referFriend: "Пригласи друга",
    friendsNamePlaceholder: "Имя друга",
    InviteFriendButton: "Пригласить друга",
    InviteMessage: "Эй, {name}, присоединяйся ко мне на этой удивительной платформе! Нажмите на ссылку ниже, чтобы начать:",
    referAFriend: "Пригласить друга",
    inviteFriend: "Пригласить друга через Telegram",
    friendName: "Имя друга",
    sendInvite: "Отправить приглашение",
    inviteSent: "Приглашение успешно отправлено!",
    alreadyReferred: "Этот пользователь уже был приглашен.",
    error: "Произошла ошибка. Попробуйте еще раз.",
    createEvent: "Создать Событие",
    eventTitle: "Название События",
    eventDescription: "Описание События",
    educationalVideoUrl: "Ссылка На Обучающее Видео",
    expirationDate: "Дата Истечения",
    eventCreated: "Событие Создано",
    eventCreationSuccessMessage: "Событие успешно создано",
    close: "Закрыть",
    home: "Главная",
    admin: "Админ",
    referral: "Реферал",
    notifications: "Уведомления",
    nonewnotifications: "У вас нет новых уведомлений.",
    referralName: "Название Приглоса",
    successfulInvites: "Успешные приглашения",
    rank: "Лвл",
    username: "Псевдоним",
    eventTitleRu: "Название мероприятия на русском языке",
    eventDescriptionRu: "Описание события на русском языке",
    level: "Уровень",
    play: "Играть",
    playWithUs: "Играйте с",
    startPlaying: "Начать игру",
    visitSite: "Посетить наш сайт",
    joinCommunity: "Присоединиться к сообществу",
    youtubeChannel: "Подписаться на наш YouTube",
    pending: "В процессе",
    in_progress: "Выполняется",
    completed: "Завершено",
    failed: "Не удалось",
    cancelled: "Отменено",
    not_started: "Не начато",
    referral_sent: "Реферал отправлен",
    referral_accepted: "Реферал принят",
    quest_started: "Задание начато",
    quest_completed: "Задание завершено",
    subtitle: {
      githubManager: "Менеджер GitHub",
    },
    button: {
      createBranch: "Создать ветку",
      pushFiles: "Отправить файлы в ветку",
      mergeBranch: "Слить ветку с основной",
    },
    log: {
      filePushed: "Файл {fileName} отправлен в ветку {branchName} с хэшем коммита {newCommitSha}.",
      branchMerged: "Ветка {branchName} слита с основной.",
      rollback: "Ветка {branchName} откатана к коммиту с хэшем {sha}.",
    },
    suberror: {
      createBranch: "Не удалось создать ветку",
      pushFiles: "Не удалось отправить файлы в ветку",
      mergeBranch: "Не удалось слить ветку с основной",
      rollback: "Не удалось откатить к коммиту",
      branchRequired: "Требуется название ветки",
      translationFieldsRequired: "Пожалуйста, укажите язык и предоставьте переводы.",
      updateTranslations: "Не удалось обновить переводы",
    },
    success: {
      translationsUpdated: "Переводы успешно обновлены.",
    },
    hackButton: "Взломать систему",
    congratulationsMessage: "Вы взломали систему!",
    conflictAwarenessTitle: "Осведомленность о конфликте и гуманитарная поддержка",
    realTimeUpdates: "Обновления в режиме реального времени",
    educationalResources: "Образовательные ресурсы",
    interactiveMaps: "Интерактивные карты",
    humanitarianAid: "Гуманитарная помощь и пожертвования",
    discussionForums: "Форумы для обсуждений",
    impactAnalytics: "Аналитика воздействия",
    donateNow: "Пожертвовать сейчас",
    postComment: "Оставить комментарий",
    post: "Опубликовать",
    premiumLandingPages: "Премиум Пользовательские Лэндинг-Страницы",
    requestLandingPage: "Запросить новую Лэндинг-страницу",
    landingPageName: "Название Лэндинг-страницы",
    view: "Просмотр",
    noLandingPages: "У вас еще нет пользовательских лэндинг-страниц.",
    cryptoPayment: "Крипто Платеж",
    generatePaymentLink: "Сгенерировать ссылку на оплату",
    paymentLinkGenerated: "Ссылка на оплату была сгенерирована:",
    invalidAmount: "Недопустимая сумма.",
    errorGeneratingLink: "Ошибка при создании ссылки на оплату.",
    defaultLabel: "ХЗ",
    disableOptionLabel: "Услугу не предоставляю",
  
    rentsTitle: "Мои Аренды",
    addNewItem: "Добавить Новый Элемент",
    activeRentals: "Активные Аренды",
    itemTitle: "Название Элемента",
    rentStart: "Начало Аренды",
    rentEnd: "Конец Аренды",
    newItems: "Новые Элементы",
    creatorShop: "Магазин Создателя",
    addNewItemTitle: "Добавить Новый Элемент",
    addNewItemDescription: "Заполните детали для нового элемента",
    formTypes: {
      evo: "Эвакуатор",
      car: "Машина",
      motorbike: "Мотоцикл",
      bicycle: "Велосипед",
      dota2: "Dota 2",
      promtgramming: "ПРОМТграммирование",
      AI: "AI",
    },
  
    // Form Labels
    selectCity: "Выберите город",
    enterYourName: "Введите ваше имя",
    mobileNumber: "Номер мобильного телефона",
    landlineNumber: "Номер городского телефона",
    email: "Ваш email",
    parkingAddress: "Адрес стоянки эвакуатора",
    adTitle: "Заголовок объявления",
    adDescription: "Описание объявления",
    cars: "Легковые автомобили",
    motorcycles: "Мототехника",
    suvs: "Внедорожники",
    minibus: "Микроавтобус",
    suburbanTariff: "Загородный тариф",
    attachPhoto: "Прикрепите фотографию",
    agreeToTerms: "Я соглашаюсь с правилами использования сервиса и с передачей и обработкой моих данных.",
    
    // Buttons
    upload: "Загрузить",
    // Add more translations...
  errorProcessingWithdrawal: "Ошибка при обработке вывода",
  cryptoWithdrawal: "Криптовывод",
  processWithdrawal: "Обработать вывод",
  withdrawalProcessed: "Вывод успешно обработан",
  cryptoManagement: "Управление криптовалютой",
  site: "Сайт",
  telegramUsername: "Имя пользователя в Telegram",
  walletAddress: "Адрес кошелька",
  payment: {
    title: "Оплата",
    description: "Описание процесса оплаты"
  },
  adInfo: {
    
    titleLabel: "Название",
    descriptionLabel: "Описание",
    title: "Информация об объявлении",
    fields: {
      title: "Заголовок объявления",
      description: "Описание объявления",
    },
  },
  agreement: {
    title: "Согласие",
    fields: {
      consent: "Я соглашаюсь с правилами использования сервиса...",
    },
  },
  generalInfo: {
    makeLabel: "Марка",
    yearLabel: "Год",
    coloLlabel: "Цвет",
    modelLabel: "Модель",
    pricLabel: "Цена",
    title: "Общая информация",
    fields: {
      make: "Марка",
      model: "Модель",
      year: "Год выпуска",
      color: "Цвет",
      price: "Цена",
      mileage: "Пробег",
    },
  },
  photoUpload: {
    photoLabel: "Фото",
    photoAlt: "Фото предмета",
    title: "Фото",
    fields: {
      photo: "Фотография",
    },
  },
  rentStartDate: "Дата начала аренды",
  rentEndDate: "Дата окончания аренды",
  calculatePrice: "Рассчитать цену",
  totalPrice: "Общая цена",
  
  proceedToPayment: "Перейти к оплате",
  itemDetailsTitle: "Cведения об элементе",
      itemDetailsDescription: "Описание",

  common: {
    n_a: "Нет данных"
  },
  save: "Сохранить новый тип элемента",
  gpt: "Упс! Не удалось разобрать этот JSON. Нужна помощь? Проверьте вкладку Разработчик!",
  gptTypeName: "Эй! Такое имя уже есть. Попробуйте что-то уникальное.",
  emptyTypeName: "Упс! Вы забыли дать имя. Без него не сохранить!",
  enterTitleKey: "Введите классное название для нового типа элемента",
  enterJsonData: "Вставьте свою магию JSON сюда",
  errorInsert: "Ой! Что-то пошло не так при сохранении. Попробуйте снова.",
  noData: "Нет данных",
  city: "Город",
  russian: "Русский",
  yourEmail: "Ваш email",
  pricing:{
    title: "Цены",
    options: "Варианты тарифов",
  },
  photos: "Фото",
  rentalStartDate: "Дата начала аренды",
  rentalEndDate: "Дата окончания аренды",
  carsCount: "Легковые автомобили",
  suvsCount: "Внедорожники",
  minibusCount: "Микроавтобус",
  motorcyclesCount: "Мототехника",
  suburbanTariffCount: "Пригородный тариф",
  dota2: "Dota 2",
nickname: "Псевдоним",
tiltLevel: "Уровень тильта",
noTilt: "Не тильтую",
discordTag: "Discord Тег",
memeBuilds: "Мем-билды",
soloLesson: "Соло урок",
partyLesson: "Пати урок",
favoriteHero: "Любимый герой",
preferredRole: "Предпочтительная роль",
support: "Поддержка",
replayAnalysis: "Анализ реплея",
inGameCoaching: "Внутриигровое обучение",
make: "Марка",
year: "Год",
color: "Цвет",
model: "Модель",
price: "Цена",
agreementSectionTitle: "Согласие",
car: "Автомобиль",
motorbike: "Мотоцикл",
bicycle: "Велосипед",
evo: "Эвакуатор",
ai: "ИИ",
groupLesson: "Групповая Мозголомка",
promptReview: "Распил Промптов",
projectAssistance: "Проектная Поддержка",
promtgramming: "Кодомантия",
darkTheme: "Темная тема",
shufle: "Перетасовать карты",
presets: "Пресеты",
selectPreset: "Выберите пресет",
gravity: "Гравитация",
airFriction: "Сопротивление воздуха",
surfaceFriction: "Сопротивление поверхности",
mass: "Масса",
liftCoefficient: "Коэффициент подъема",
minRotationSpeedForLift: "Мин. скорость вращения для подъема",
"Lunar Gravity": "Лунная гравитация",
"Earth Gravity": "Земная гравитация",
"No Air Friction": "Без воздушного сопротивления",
"Jupiter Gravity": "Гравитация Юпитера",
}
