import { LanguageDictionary } from "../utils/TranslationUtils";
export const ukr: LanguageDictionary = {
  pleaseGrantAccess: "Будь ласка, надайте доступ до своєї камери та мікрофона для гри.",
  checkPermissions: "Перевірка дозволів",
  "settings": {
    "title": "Налаштування",
    "restoreDefaults": "Включити чарівність (або повернути заводські налаштування)",
    "yeetCoefficient": "Коефіцієнт 'Йіт' (Потужність твоїх викидів)",
    "mass": "Маса (Скільки важить твій кумедний 'йіт')",
    "tension": "Напруження (Як перед іспитом)",
    "friction": "Стискання (Якщо спробуєш бути гладким)",
    "rotationDistance": "Відстань обертання (Не для спіральних танців)",
    "yeetVelocityThreshold": "Поріг 'Йіта' (Щоб не злетіти до зірок)",
    "minMovementThreshold": "Мінімальний поріг руху (Не для лінивих)",
    "github": "Переглянути на GitHub (Місце, де код грає в хованки)",
    "version": "Версія 0.13 (Близько до 0.14, але без сюрпризів)"
  },
  "physicsSettings":  "Налаштування",
  "yeetCoefficient": "Коефіцієнт викиду",
  "tension": "Напруга",
  "rotationDistance": "Відстань обертання",
  "friction": "Тертя",
  "yeetVelocityThreshold": "Поріг швидкості викиду",
  "minMovementThreshold": "Мінімальний поріг руху",
  applySettings: "Застосувати",
    defaultLabel: "ХЗ",
    conflictAwarenessTitle: "Усвідомлення конфлікту та гуманітарна підтримка",
    realTimeUpdates: "Оновлення в режимі реального часу",
    educationalResources: "Освітні ресурси",
    interactiveMaps: "Інтерактивні карти",
    humanitarianAid: "Гуманітарна допомога та пожертви",
    discussionForums: "Форуми для обговорень",
    impactAnalytics: "Аналіз впливу",
    donateNow: "Пожертвувати зараз",
    postComment: "Залишити коментар",
    post: "Опублікувати",
    emotionMirror: "Дзеркало емоцій",
    typeMessage: "Введіть ваше повідомлення...",
    clear: "Очистити",
    about: {
      info: 'Інформація',
      title: 'Про додаток',
      motto: 'Додаток створений для вільного створення web3-середовищ і підтримує комерційне використання через криптовалюти.',
      github: 'Подивитися на GitHub',
      version: 'Додаток v. 0.13',
    },
  developerToolTitle: "Інструмент розробника",
  currentIdeasTitle: "Поточні ідеї",
  enterYourIdeaTitle: "Введіть свою ідею",
  describeYourIdeaPlaceholder: "Опишіть свою ідею...",
  generateRequestButton: "Створити запит",
  zeroStageRequestTitle: "Запит на нульовий етап",
  getResponseButton: "Отримати відповідь із буфера обміну",
parsedResponseDataTitle: "Проаналізовані дані відповіді",
  branchNameTitle: "Назва гілки",
  componentImplementationsTitle: "Реалізації компонентів",
  translationKeysTitle: "Ключі перекладу",
  supabaseTablesTitle: "Надбазові таблиці",
  readmeUpdateTitle: "Оновлення README.md",
  tryItButton: "Спробуйте",
  deployButton: "Розгорнути",
contributorsLabel: "Учасники",
    questsTitle: "Завдання для заробітку монет",
    inviteFriends: "Запросіть друзів",
    inviteFriendsDescription: "Запросіть 3 друзів через реферальне посилання, щоб заробити монети.",
    inviteFriendsAction: "Запросити зараз",
    createFeature: "Створіть свою першу функцію",
    createFeatureDescription: "Створіть свою першу функцію в режимі розробки, щоб заробити монети.",
    createFeatureAction: "Створити функцію",
    claimReward: "Отримати нагороду",
    hackButton: "Зламати систему",
    congratulationsMessage: "Ви зламали систему!",
    copy: "Копіювати запит до буфера обміну",
    notifications: "Сповіщення",
    confirm: "Підтвердити",
    name: "Українська",
    welcome: "Ласкаво просимо",
    task: "Завдання",
    description: "Опис",
    addTask: "Додати завдання",
    complete: "Завершити",
    delete: "Видалити",
    active: "Активний",
    activeBets: "Активні ставки та події",сума: "Сума",
    outcome: "Результат",
    status: "Статус",
    upcomingEvents: "Майбутні події",
    title: "Назва",
    actions: "Дії",
    expired: "Минув",
    bet: "Натиск",
    placeBet: "Зробити ставку",
    enterBetAmount: "Введіть суму ставки",
    calcTitle: "Калькулятор IQ/соціальних показників",
    referFriend: "Запропонуйте другу",
    friendNamePlaceholder: "Ім'я друга",
    inviteFriendButton: "Запросити друга",
    inviteMessage: "Привіт, {name}, приєднуйся до мене на цій дивовижній платформі! Натисніть посилання нижче, щоб почати:",
    referAFriend: "Запропонуйте другу",
    inviteFriend: "Запросити друга через Telegram",
    friendName: "Ім'я друга",
    sendInvite: "Надіслати запрошення",
    inviteSent: "Запрошення надіслано успішно!",
    alreadyReferred: "Цього користувача вже було направлено.",
    error: "Сталася помилка. Повторіть спробу.",
    profile: "Профіль",
    createEvent: "Створити Подію",
    eventTitle: "Назва Події",
    eventDescription: "Опис Події",
    educationalVideoUrl: "URL Освітнього Відео",
    expirationDate: "Дата Закінчення",
    eventCreated: "Подію Створено",
    eventCreationSuccessMessage: "Подію успішно створено",
    close: "Закрити",
    home: "Головна",
    admin: "Адмін",
    referral: "Реферал",
    referralName: "Ім'я Пріглоса",
    successfulInvites: "Успішні запрошення",
    rank: "Лвл",
    username: "Псевдонім",
    eventTitleRu: "Назва події російською",
    eventDescriptionRu: "Опис події російською мовою",
    adminDashboard: "Панель адміністратора",
    referrer: "Реферер",
    referee: "Рефері",
    level: "Рівень",
    date: "Дата",
    nonewnotifications: "У вас немає нових повідомлень.",
    play: "Грати",
    playWithUs: "Грай з",
    startPlaying: "Почати гру",
    visitSite: "Відвідати наш сайт",
    joinCommunity: "Приєднатися до спільноти",
    youtubeChannel: "Підписатися на наш YouTube",
    profilePicture: "Фото профілю",
    userId: "ID",
    coins: "Монети",
    rp: "Очки репутації",
    X: "X Очки",
    cheers_count: "Кількість оплесків",
    social_credit: "Соціальний рейтинг",
    ref_code: "Реферальний код",
    currentGameId: "ID поточної гри",
    none: "Немає",
    pending: "В очікуванні",
    in_progress: "Виконується",
    completed: "Завершено",
    failed: "Не вдалося",
    cancelled: "Скасовано",
    not_started: "Не розпочато",
    referral_sent: "Реферал відправлено",
    referral_accepted: "Реферал прийнято",
    quest_started: "Завдання розпочато",
    quest_completed: "Завдання завершено",
    totalReferrals: "Загальна кількість рефералів",
    referralsLastMonth: "Реферали за минулий місяць",
    referralsLastYear: "Реферали за минулий рік",
    refCode: "Код реферала",
    referralsByCode: "Реферали за кодом",
    referrals: "Реферали",
    subtitle: {
        githubManager: "Менеджер GitHub",
    },
    button: {
        createBranch: "Створити гілку",
        pushFiles: "Надіслати файли до гілки",
        mergeBranch: "Об'єднати гілку з головною",
    },
    журнал: {
        filePushed: "Файл {fileName} направлено до гілки {branchName} із SHA комітом {newCommitSha}.",
        branchMerged: "Гілку {branchName} об’єднано з основною.",
        rollback: "Гілку {branchName} повернуто до фіксації SHA {sha}.",
    },
    suberror: {
        createBranch: "Не вдалося створити гілку",
        pushFiles: "Не вдалося відправити файли до гілки",
        mergeBranch: "Не вдалося об'єднати гілку в основну",
        rollback: "Не вдалося відкотити для фіксації",
        branchRequired: "Потрібна назва гілки",
        translationFieldsRequired: "Будь ласка, вкажіть мову та надайте переклади.",
        updateTranslations: "Не вдалося оновити переклади",
    },
    success: {
        translationsUpdated: "Переклади успішно оновлено.",
    },

    premiumLandingPages: "Преміум Користувацькі Лендінг-Сторінки",
    requestLandingPage: "Запросити нову Лендінг-сторінку",
    landingPageName: "Назва Лендінг-сторінки",
    view: "Перегляд",
    noLandingPages: "У вас ще немає користувацьких лендінг-сторінок.",
    cryptoPayment: "Крипто Платіж",
    amount: "Сума",
    generatePaymentLink: "Згенерувати посилання на оплату",
    paymentLinkGenerated: "Посилання на оплату було згенеровано:",
    invalidAmount: "Недійсна сума.",
    errorGeneratingLink: "Помилка при створенні посилання на оплату.",
    qrCodeTitle: "Продовжити на іншому пристрої",
    qrCodeDescription: "Скануйте цей QR-код на своєму мобільному пристрої, щоб продовжити заповнення форми.",
    generateQrCode: "Згенерувати QR-код",
    dynamicForm: "Динамічна форма",
    submit: "Надіслати",
    itemAddedSuccessfully: "Елемент успішно додано, будь ласка, оновіть сторінку",
    paymentSuccessMessage: "Привіт, {username}! Ваш платіж пройшов успішно. Преміум доступ буде активовано до {activationDate}.",
    notificationSent: "Повідомлення успішно надіслано!",
    resendNotification: "Відправити повідомлення ще раз",
    saveAndContinueInTelegram: "Зберегти та продовжити в Telegram",
    disableOptionLabel: "Сервіс не надається",
    
    rentsTitle: "Мої Оренди",
    addNewItem: "Додати Новий Елемент",
    activeRentals: "Активні Оренди",
    itemTitle: "Назва Елемента",
    rentStart: "Початок Оренди",
    rentEnd: "Кінець Оренди",
    newItems: "Нові Елементи",
    creatorShop: "Магазин Творця",
    addNewItemTitle: "Додати Новий Елемент",
    addNewItemDescription: "Заповніть деталі для нового елемента",
    formTypes: {
      evo: "Евакуатор",
      car: "Машина",
      motorbike: "Мотоцикл",
      bicycle: "Велосипед",
      dota2: "Dota 2",
      promtgramming: "Прогтрамування",
      AI: "AI",
    },
  
    // Form Labels
    selectCity: "Виберіть місто",
    enterYourName: "Введіть ваше ім'я",
    mobileNumber: "Номер мобільного телефону",
    landlineNumber: "Номер стаціонарного телефону",
    email: "Ваш email",
    parkingAddress: "Адреса стоянки евакуатора",
    adTitle: "Заголовок оголошення",
    adDescription: "Опис оголошення",
    cars: "Легкові автомобілі",
    motorcycles: "Мотоцикли",
    suvs: "Позашляховики",
    minibus: "Мікроавтобус",
    suburbanTariff: "Замісто тариф",
    attachPhoto: "Додати фото",
    agreeToTerms: "Я погоджуюсь з умовами використання сервісу та обробкою моїх даних.",
    
    // Buttons
    upload: "Завантажити",
    rent: "Оренда",
    // Add more translations...
  errorProcessingWithdrawal: "Помилка при обробці виводу",
  cryptoWithdrawal: "Криптовиведення",
  processWithdrawal: "Обробити виведення",
  withdrawalProcessed: "Виведення успішно оброблено",
  cryptoManagement: "Управління криптовалютою",
  site: "Сайт",
  telegramUsername: "Ім'я користувача в Telegram",
  walletAddress: "Адреса гаманця",
  payment: {
    title: "Payment",
    description: "Description of payment process"
  },
  adInfo: {
    titleLabel: "Назва",
    descriptionLabel: "Опис",
    title: "Ad information",
    fields: {
      title: "Ad title",
      description: "Ad description",
    },
  },
  agreement: {
    title: "Consent",
    fields: {
        consent: "I agree with the terms of use of the service...",
    },
  },
generalInfo: {
    makeLabel: "Марка",
    yearLabel: "Рік",
    colorLabel: "Колір",
    modelLabel: "Модель",
    priceLabel: "Ціна",
    title: "General information",
    fields: {
      make: "Brand",
      model: "Model",
      year: "Year of issue",
      color: "Color",
      price: "Price",
      mileage: "Mileage",
    },
  },
  photoUpload: {
    photoLabel: "Фото",
    photoAlt: "Фото предмета",
    title: "Photo",
    fields: {
        photo: "Photography",
    },
    
  },
  rentStartDate: "Дата початку оренди",
      rentEndDate: "Дата закінчення оренди",
      calculatePrice: "Обчислити ціну",
      totalPrice: "Загальна ціна",
      proceedToPayment: "Перейти до оплати",
      itemDetailsTitle: "Назва подробиць елемента",
      itemDetailsDescription: "Опис подробиць елемента",
      newRentNotification: "Хтось намагався орендувати ваш товар",
      viewItem: "Переглянути елемент",
      common: {
        n_a: "Немає даних",
      },
      newItemTypeNameRequest: "Введіть назву для нового типу елемента:",
      saveRefCode: "Зберегти",
      save: "Зберегти новий тип елемента",
      gpt: "Ой! Не вдалося розібрати цей JSON. Потрібна допомога? Перевірте вкладку Розробник!",
      gptTypeName: "Гей! Таке ім'я вже є. Спробуйте щось унікальне.",
      emptyTypeName: "Ой! Ви забули дати ім'я. Без нього не зберегти!",
      enterTitleKey: "Введіть круту назву для нового типу елемента",
      enterJsonData: "Вставте свою JSON-магію сюди",
      errorInsert: "Ой! Щось пішло не так під час збереження. Спробуйте знову.",
      noData: "Немає даних",
      city: "Місто",
      russian: "Російська",
      yourEmail: "Ваш email",
      pricing:{
        title: "Ціни",
        options: "Варіанти тарифів",
      },
      photos: "Фото",
      rentalStartDate: "Дата початку оренди",
      rentalEndDate: "Дата закінчення оренди",
      carsCount: "Легкові автомобілі",
      suvsCount: "Позашляховики",
      minibusCount: "Мікроавтобус",
      motorcyclesCount: "Мототехніка",
      suburbanTariffCount: "Приміський тариф",
      dota2: "Dota 2",
ff: "ФФ",
nickname: "Псевдонім",
dcfc: "ДЦФЦ",
tiltLevel: "Рівень тильту",
noTilt: "Не тильтую",
discordTag: "Discord Тег",
memeBuilds: "Мем-білди",
soloLesson: "Соло урок",
partyLesson: "Паті урок",
favoriteHero: "Улюблений герой",
preferredRole: "Улюблена роль",
support: "Підтримка",
replayAnalysis: "Аналіз повтору",
inGameCoaching: "Навчання в грі",
make: "Марка",
year: "Рік",
color: "Колір",
model: "Модель",
price: "Ціна",
agreementSectionTitle: "Згода",
car: "Автомобіль",
motorbike: "Мотоцикл",
bicycle: "Велосипед",
evo: "Евакуатор",
ai: "ШІ",
groupLesson: "Групова Мозголомка",
promptReview: "Розпил Промптів",
projectAssistance: "Проектна Допомога",
promtgramming: "Кодоманія",
darkTheme: "Темна тема",
shuffle: "перетасувати карти",
shuffling: "Тасу каоти..",
presets: "Пресети",
selectPreset: "Оберіть пресет",
gravity: "Гравітація",
airFriction: "Опір повітря",
surfaceFriction: "Опір поверхні",
mass: "Маса",
liftCoefficient: "Коефіцієнт підйому",
minRotationSpeedForLift: "Мін. швидкість обертання для підйому",
"Lunar Gravity": "Місячна гравітація",
"Earth Gravity": "Земна гравітація",
"No Air Friction": "Без повітряного опору",
"Jupiter Gravity": "Гравітація Юпітера",
generateRequestButton4type: "Створити запит нового типу",
createTask: "Створити завдання",
  serverName: "Ім'я сервера",
  membersNeeded: "Потрібні учасники",
  activeTasks: "Активні завдання",
  deleteTask: "Видалити завдання",
  userPoints: "Бали користувача",
  serverId: "Ідентифікатор сервера",
  points: "Точки",
  tasks: "Завдання",
  users: "Користувачі",
  promoteToAdmin: "Підвищити до адміністратора",
  role: "Роль",
  socialCredit: "Соціальний кредит",
  inviteLink: "Посилання для запрошення",
  adminData: "Дані адміна",
  subscriptions: "Підписки",
  botMessages: "Повідомлення бота",
  rewardPoint: "Нагородний бал",
  checkSubscription: "Перевірити підписку",
  taskId: "Ідентифікатор завдання",
  createQuest: "Створити квест",
  questTitle: "Назва квесту",
  questDescription: "Опис квесту",
  questType: "Тип квесту",
  questReward: "Нагорода за квест",
  questCategory: "Категорія квесту",
  questImageUrl: "URL-адреса зображення квесту",
  questTarget: "Ціль квесту",
  questSocialLink: "Посилання на соціальні квести",
  tracking: "Відстеження",
  social: "Соціальний",
  questStates: "Стани завдання",
  activeQuests: "Активні квести",
  deleteQuest: "Видалити квест",
  questId: "Ідентифікатор квесту",
  state: "Держава",
  progress: "Прогрес",
  streak: "Смуга",
  checkReferrals: "Перевірити рефералів",
  referedUserId: "Ідентифікатор рекомендованого користувача",
  search: "Пошук",
  quests: "Квесты",
  totalUsers: "Всего пользователей",
  cryptopayment: "₿",
  avatarUrl: "Посилання на зображення аватара",
  playCards: "Грати в карти",
  playDice: "Грати в кості",
  backToMenu: "Повернутися до меню",
  userNotFound: "Користувача не знайдено",
  updateCoinsError: "Помилка оновлення монет",
  generalError: "Сталася помилка. Будь ласка, спробуйте ще раз.",
  diceGame: "Гра в кості",
  score: "Рахунок",
  player1: "Гравець 1",
  player2: "Гравець 2",
  rollDice: "Кинути кості",
  newGame: "Нова гра",
  twoPlayerMode: "Режим на двох",
  aiMode: "Гра з ШІ",
  randomOpponentMode: "Випадковий суперник",
  backToSinglePlayer: "Повернутися до одиночної гри",
  rules: "Правила",
  rulesText: "Кидайте кості та намагайтеся набрати найбільшу кількість очок. У режимі на двох гравці кидають кості по черзі. Перемагає гравець з найбільшою кількістю очок!",
  rolling: "Котиться...",
  singlePlayer: "Один гравець",
  twoPlayer: "Два гравці",
  playWithAI: "Грати з AI",
  randomOpponent: "Випадковий суперник",
  winner: "Переможець",
  noActiveGame: "Активної гри не знайдено",
  updateError: "Помилка оновлення",
  updateErrorDescription: "Не вдалося оновити стан гри. Спробуйте ще раз.",
  hackSuccess: "Злом виконано успішно",
  newGameAdded: "Нова гра додана до списку",
  hackError: "Помилка злому",
  tryAgainLater: "Спробуйте пізніше",
  hacking: "Злом...",
  hack: "Зламати",
  currentTurn: "Твоя черга",
  turn: "черга",
}
